import Link from "next/link";
import Logo from "@/app/components/Logo";

const SANS = "'IBM Plex Sans', sans-serif";
const SERIF = "'IBM Plex Serif', serif";
const MONO = "'IBM Plex Mono', monospace";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 28 }}>
      <h2 style={{ fontFamily: SERIF, fontWeight: 600, fontSize: 17, color: "var(--t-text)", margin: "0 0 10px" }}>{title}</h2>
      <div style={{ fontSize: 14, lineHeight: 1.7, color: "var(--t-text-secondary)" }}>{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--t-bg)", fontFamily: SANS }}>
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px 80px" }}>
        <Link href="/" style={{ display: "inline-flex", alignItems: "center", gap: 9, textDecoration: "none", marginBottom: 32 }}>
          <Logo size={26} />
          <span style={{ fontWeight: 600, fontSize: 17, letterSpacing: "-0.01em", color: "var(--t-text)", fontFamily: SANS }}>Finance Companion</span>
        </Link>

        <h1 style={{ fontFamily: SERIF, fontWeight: 600, fontSize: 26, color: "var(--t-text)", margin: "0 0 6px" }}>
          Terms of Use &amp; Disclaimer
        </h1>
        <p style={{ fontFamily: MONO, fontSize: 12, color: "var(--t-text-muted)", margin: "0 0 36px" }}>
          Last updated {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
        </p>

        <Section title="Not Financial Advice">
          Finance Companion ("the Service") provides AI-generated market commentary, analysis, and simulated
          portfolio tracking for informational and educational purposes only. Nothing on this Service constitutes
          financial, investment, tax, or legal advice, or a recommendation or solicitation to buy, hold, or sell
          any security, cryptocurrency, or other financial instrument. You should not rely on any content here as
          the basis for an investment decision. Always conduct your own research and consult a licensed financial
          advisor, accountant, or attorney before acting.
        </Section>

        <Section title="AI-Generated Content">
          Verdicts, price targets, risk scenarios, news summaries, and portfolio commentary are generated by
          large language models (Anthropic Claude) and automated analysis pipelines. AI-generated output can be
          incomplete, outdated, or factually incorrect, and may misinterpret market data or news. It is not
          reviewed by a human analyst before being shown to you.
        </Section>

        <Section title="No Warranty on Data or Accuracy">
          Market data, prices, technical indicators, earnings dates, and news are sourced from third-party
          providers (including yfinance and Finnhub) and may be delayed, incomplete, or inaccurate. The Service
          is provided "as is" and "as available," without warranties of any kind, express or implied, including
          accuracy, timeliness, merchantability, or fitness for a particular purpose.
        </Section>

        <Section title="Limitation of Liability">
          To the fullest extent permitted by law, the operator of Finance Companion shall not be liable for any
          direct, indirect, incidental, consequential, or special damages — including trading losses, lost
          profits, or lost data — arising from your use of, or inability to use, the Service, or from any
          reliance placed on its content. You use the Service, and make any investment decisions, entirely at
          your own risk.
        </Section>

        <Section title="Simulated Portfolios">
          "Autopilot" and "Co-pilot" simulation modes track hypothetical, virtual-currency positions only. They
          do not execute real trades, do not connect to a brokerage, and their performance does not represent or
          guarantee the performance of any real investment.
        </Section>

        <Section title="Intellectual Property">
          The Finance Companion name, logo, interface design, and original written content are the property of
          the Service operator and may not be copied, reproduced, or redistributed without permission. Market
          data and third-party content remain the property of their respective providers. AI-generated analysis
          is provided for your personal, non-commercial use.
        </Section>

        <Section title="Your Account & Responsibilities">
          You are responsible for maintaining the confidentiality of your account and for all activity under it.
          You must be legally permitted to use investment research tools in your jurisdiction. Holdings and
          watchlist data you enter are used solely to generate your personalized digest and analysis.
        </Section>

        <Section title="Changes to These Terms">
          These terms may be updated from time to time as the Service evolves. Continued use of the Service after
          changes are posted constitutes acceptance of the revised terms.
        </Section>

        <Section title="Copyright">
          © {new Date().getFullYear()} Finance Companion. All rights reserved.
        </Section>
      </div>
    </div>
  );
}
